# Generated by Django 6.0.5 on 2026-06-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
