# Generated by Django 6.0.5 on 2026-06-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_category_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='category',
        ),
    ]
