# Generated by Django 6.0.5 on 2026-06-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_rename_category_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
